import 'package:freezed_annotation/freezed_annotation.dart';

part 'agent_legal.freezed.dart';
part 'agent_legal.g.dart';

@freezed
class AgentLegal with _$AgentLegal {
  const factory AgentLegal({
    @Default(true) bool autoGeneratedTerms,
    String? termsUrl,
  }) = _AgentLegal;

  factory AgentLegal.fromJson(Map<String, dynamic> json) =>
      _$AgentLegalFromJson(json);
}
