// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:viralmind_flutter/frb_generated.dart/frb_generated.dart';

ToolsStatus checkToolsStatus() =>
    RustLib.instance.api.crateApiToolsCheckToolsStatus();

Future<List<String>> initTools() =>
    RustLib.instance.api.crateApiToolsInitTools();

class ToolsStatus {
  const ToolsStatus({
    required this.ffmpeg,
    required this.ffprobe,
    required this.dumpTree,
    required this.pipeline,
  });
  final bool ffmpeg;
  final bool ffprobe;
  final bool dumpTree;
  final bool pipeline;

  @override
  int get hashCode =>
      ffmpeg.hashCode ^
      ffprobe.hashCode ^
      dumpTree.hashCode ^
      pipeline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToolsStatus &&
          runtimeType == other.runtimeType &&
          ffmpeg == other.ffmpeg &&
          ffprobe == other.ffprobe &&
          dumpTree == other.dumpTree &&
          pipeline == other.pipeline;
}
