// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'agent_legal.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#adding-getters-and-methods-to-our-models');

AgentLegal _$AgentLegalFromJson(Map<String, dynamic> json) {
  return _AgentLegal.fromJson(json);
}

/// @nodoc
mixin _$AgentLegal {
  bool get autoGeneratedTerms => throw _privateConstructorUsedError;
  String? get termsUrl => throw _privateConstructorUsedError;

  /// Serializes this AgentLegal to a JSON map.
  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;

  /// Create a copy of AgentLegal
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  $AgentLegalCopyWith<AgentLegal> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $AgentLegalCopyWith<$Res> {
  factory $AgentLegalCopyWith(
          AgentLegal value, $Res Function(AgentLegal) then) =
      _$AgentLegalCopyWithImpl<$Res, AgentLegal>;
  @useResult
  $Res call({bool autoGeneratedTerms, String? termsUrl});
}

/// @nodoc
class _$AgentLegalCopyWithImpl<$Res, $Val extends AgentLegal>
    implements $AgentLegalCopyWith<$Res> {
  _$AgentLegalCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  /// Create a copy of AgentLegal
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? autoGeneratedTerms = null,
    Object? termsUrl = freezed,
  }) {
    return _then(_value.copyWith(
      autoGeneratedTerms: null == autoGeneratedTerms
          ? _value.autoGeneratedTerms
          : autoGeneratedTerms // ignore: cast_nullable_to_non_nullable
              as bool,
      termsUrl: freezed == termsUrl
          ? _value.termsUrl
          : termsUrl // ignore: cast_nullable_to_non_nullable
              as String?,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$AgentLegalImplCopyWith<$Res>
    implements $AgentLegalCopyWith<$Res> {
  factory _$$AgentLegalImplCopyWith(
          _$AgentLegalImpl value, $Res Function(_$AgentLegalImpl) then) =
      __$$AgentLegalImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call({bool autoGeneratedTerms, String? termsUrl});
}

/// @nodoc
class __$$AgentLegalImplCopyWithImpl<$Res>
    extends _$AgentLegalCopyWithImpl<$Res, _$AgentLegalImpl>
    implements _$$AgentLegalImplCopyWith<$Res> {
  __$$AgentLegalImplCopyWithImpl(
      _$AgentLegalImpl _value, $Res Function(_$AgentLegalImpl) _then)
      : super(_value, _then);

  /// Create a copy of AgentLegal
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? autoGeneratedTerms = null,
    Object? termsUrl = freezed,
  }) {
    return _then(_$AgentLegalImpl(
      autoGeneratedTerms: null == autoGeneratedTerms
          ? _value.autoGeneratedTerms
          : autoGeneratedTerms // ignore: cast_nullable_to_non_nullable
              as bool,
      termsUrl: freezed == termsUrl
          ? _value.termsUrl
          : termsUrl // ignore: cast_nullable_to_non_nullable
              as String?,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$AgentLegalImpl implements _AgentLegal {
  const _$AgentLegalImpl({this.autoGeneratedTerms = true, this.termsUrl});

  factory _$AgentLegalImpl.fromJson(Map<String, dynamic> json) =>
      _$$AgentLegalImplFromJson(json);

  @override
  @JsonKey()
  final bool autoGeneratedTerms;
  @override
  final String? termsUrl;

  @override
  String toString() {
    return 'AgentLegal(autoGeneratedTerms: $autoGeneratedTerms, termsUrl: $termsUrl)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$AgentLegalImpl &&
            (identical(other.autoGeneratedTerms, autoGeneratedTerms) ||
                other.autoGeneratedTerms == autoGeneratedTerms) &&
            (identical(other.termsUrl, termsUrl) ||
                other.termsUrl == termsUrl));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode => Object.hash(runtimeType, autoGeneratedTerms, termsUrl);

  /// Create a copy of AgentLegal
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  @pragma('vm:prefer-inline')
  _$$AgentLegalImplCopyWith<_$AgentLegalImpl> get copyWith =>
      __$$AgentLegalImplCopyWithImpl<_$AgentLegalImpl>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$AgentLegalImplToJson(
      this,
    );
  }
}

abstract class _AgentLegal implements AgentLegal {
  const factory _AgentLegal(
      {final bool autoGeneratedTerms,
      final String? termsUrl}) = _$AgentLegalImpl;

  factory _AgentLegal.fromJson(Map<String, dynamic> json) =
      _$AgentLegalImpl.fromJson;

  @override
  bool get autoGeneratedTerms;
  @override
  String? get termsUrl;

  /// Create a copy of AgentLegal
  /// with the given fields replaced by the non-null parameter values.
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  _$$AgentLegalImplCopyWith<_$AgentLegalImpl> get copyWith =>
      throw _privateConstructorUsedError;
}
