// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'agent_legal.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$AgentLegalImpl _$$AgentLegalImplFromJson(Map<String, dynamic> json) =>
    _$AgentLegalImpl(
      autoGeneratedTerms: json['autoGeneratedTerms'] as bool? ?? true,
      termsUrl: json['termsUrl'] as String?,
    );

Map<String, dynamic> _$$AgentLegalImplToJson(_$AgentLegalImpl instance) =>
    <String, dynamic>{
      'autoGeneratedTerms': instance.autoGeneratedTerms,
      'termsUrl': instance.termsUrl,
    };
